apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: lab-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 476114143297.dkr.ecr.ap-southeast-1.amazonaws.com/order-service:1f67cdf
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          env:
            - name: PORT
              value: "5002"
            - name: ENVIRONMENT
              value: "staging"
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: lab-staging
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 5002
      targetPort: 5002
  type: ClusterIP
